import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import {Header} from "@/components/Header";
import {Container} from "@/components/Container";

export const metadata: Metadata = {
  title: {
      default: "The Blog Dev - Criado para DEVs",
      template: "%s | The Blog Dev",
  },
  description: "Generated by create next app",
};

type RootlayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: Readonly<RootlayoutProps>) {
  return (
      <html lang="pt-BR">
      <body>
      <Container >
          <Header />
          {children}
          <footer >
              <p className="text-6xl font-bold text-center py-8">FOOTER</p >
          </footer >
      </Container >
      </body>
    </html>
  );
}
