import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import {Header} from "@/components/Header";
import {Container} from "@/components/Container";
import {Footer} from "@/components/Footer";

export const metadata: Metadata = {
  title: {
      default: "The Dev Blog - Criado para DEVs",
      template: "%s | The Dev Blog",
  },
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
      <html lang="pt-BR">
      <body>
      <Container >
          <Header />
          {children}
          <Footer />
      </Container >
      </body>
    </html>
  );
}
